spring.application.name=msvc-student

server.port=8090
eureka.instance.hostname=msvc-student

eureka.client.service-url.defaultZone=http://msvc-eureka:8761/eureka

#   Configuration for DB
spring.datasource.url=${STUDENT_DB_URL}
spring.datasource.username=${STUDENT_DB_USERNAME}
spring.datasource.password=${STUDENT_DB_PASSWORD}
spring.datasource.drive-class-name=com.mysql.jdbc.Drive
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.initialization-mode=always

spring.config.import=optional:configserver:http://localhost:8888

# Retries para MySQL
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=30000
spring.jpa.properties.hibernate.hbm2ddl.retry_attempts=5